<div class="login-section section " style="margin-bottom: 3%;">
    <div class="container">
        <div id="top-header-my-account row card" style="padding: 5% 0; background-color: white;margin: 5% 0;">
            <h1 style="background-color: white !important; color: black !important;" class="text-center"><?php echo $title; ?></h1>
        </div>
        <div class="login-section section " style="margin-bottom: 3%;">
            <!-- <h1 class="page-title">How it Works?</h1> -->
            <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:22.5pt;color: red !important;">Terms and Conditions</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Welcome to OriGamers!</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">These terms and conditions outline the rules and regulations for the use of OriGamers&apos;s Website, located at www.origamers.com.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">By accessing this website, we assume you accept these terms and conditions. Do not continue to use OriGamers if you do not agree to take all of the terms and conditions stated on this page.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: &quot;Client&quot;, &quot;You&quot; and &quot;&ldquo;Your&quot; refers to you, the person log on this website and compliant to the Company&rsquo;s terms and conditions. &quot;The Company&quot;, &quot;Ourselves&quot;, &quot;We&quot;, &quot;Our&quot; and &quot;Us&quot;, refers to our Company. &quot;Party&quot;, &quot;Parties&quot;, or &quot;Us&quot;, refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client&rsquo;s needs in respect of provision of the Company&rsquo;s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cookies</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We employ the use of cookies. By accessing OriGamers, you agreed to use cookies in agreement with the OriGamers&apos;s Privacy Policy.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Most interactive websites use cookies to let us retrieve the user&rsquo;s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Referral system&nbsp;</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In order to purchase any of the products from our website and for unlocking the discount you need to refer and join at least three friends/people.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Once you are done with payment our website provides unique refer code to the user this code is used to join people under your Id registered with us. The people joined through your referral code, purchased the same product as you did and paid the full amount are shown in green colour. The people that join through your referral code and didn&rsquo;t buy the same product that you purchased will not be considered as your referral and will remain in red colour only. Once your three referrals are turned into Green(purchased) the request for google credit voucher will be activated. Once your google credit voucher is activated kindly go to request google play voucher and submit your register e-mail. After submitting this request, you will receive google play voucher in your e-mail within 18 hours.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">NOTE: -</span><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You can only buy one product at a time. Unless and until your three referrals has not purchased and turned into green you cannot buy any other product from the website.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Refund policy</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In order to request refund, you need to fill the refund form available in our website. You&rsquo;re eligible to receive refund only till 15 days from your date of your payment. Only then your request will be accepted.</span></p>
<p><br></p>
<div align="left" dir="ltr" style="margin-left:-5.65pt;">
    <table style="border:none;border-collapse:collapse;">
        <tbody>
            <tr style="height:24.25pt;">
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Sr.no</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Conditions</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Refund percentage</span></p>
                </td>
            </tr>
            <tr style="height:21.55pt;">
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:13.999999999999998pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1</span><span style="font-size:16pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If no person has joined and purchased the same product within 15 Days from the date of your payment.</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">0 %</span></p>
                </td>
            </tr>
            <tr style="height:0pt;">
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:13.999999999999998pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If one person has joined and purchased the same product Within 15 days from the date of your payment.</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">50 %</span></p>
                </td>
            </tr>
            <tr style="height:0pt;">
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:13.999999999999998pt; color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If two people have joined and purchased the same product within 15 days from the date of your payment.</span></p>
                </td>
                <td style="border-left:solid #bfbfbf 0.5pt;border-right:solid #bfbfbf 0.5pt;border-bottom:solid #bfbfbf 0.5pt;border-top:solid #bfbfbf 0.5pt;vertical-align:top;padding:0pt 5.4pt 0pt 5.4pt;overflow:hidden;overflow-wrap:break-word;">
                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">100 %</span></p>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<p><br></p>
<p>You are not eligible for any kind of refund after 15 days from your date of purchase.</p>
<p>You must fill the refund form provided by origamers within 15 Days</p>
<p>You must correctively fill all the asked information by the origamers in the refund form. If fail to do so origamers would not be responsible for your loss.</p>
<p>The screen shot of refer section is must to verify your refund request. if any kind of fake, edited, tampered screen shot is submitted legal actions would be taken by origamers against you. In such cases no refund will be given back.</p>
<p>In order to refund your amount, you have to fill the refund form available in our website. The form contains name, email, phone number, bank details such as bank holder name, Account number, IFSC code, Bank branch. There is an option in the form to attach file, you need to attach the screenshot of how many people have joined and purchased (names shown in green colour) through your referral code.</p>
<p>NOTE: - WE CAN INCREASE OR DECREASE THE PRICE OF THE PRODUCTS ACCORDING TO THE FUTURE CONDITIONS.</p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:20pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Google Play Voucher</span></p>

<p>We use google play voucher as a medium to deliver our game products. We do not sell google play voucher. We are not the authorized seller by google we are not running any google play voucher scam. Origamers itself purchase google play voucher online and deliver the google play voucher code to our customers in their respective email after they have completed and fulfilled the above conditions. The google play voucher code we purchase and deliver to our customer remains untouched i.e. unused. The code is valid for only one product that you purchased.</p>
<p>After the request for google play voucher origamers will send your voucher at your register e-mail with us. If you have submitted the wrong or invalid e-mail to us Origamers will not be responsible for your loss</p>
<p>Origamers will send you a screenshot of the google voucher as a proof of delivering the voucher.</p>
<p>Once the Voucher and the screenshot e-mail is delivered by the origamers to the user. Origamers will not be responsible for any kind of loss.</p>
<p>Origamers will not be responsible if u share your voucher code with someone else.</p>
<p dir="ltr" style="line-height:1.2;margin-left: 22.5pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Violations</span></p>
<p>If anyone tries to commit fraud or steal data or tries to fool the website in any manner. Strict actions will be taken against you and you will be prohibited from using our website.</p>
<p>Copying our website or using our website name in any way is strictly prohibited. If do so legal actions will be taken against you.</p>
<p>False accusation towards our website name would not be entertained and legal actions would be taken by us.</p>
<p>If anyone tries to violate our terms and conditions will not be entertained and will be prohibited from using our website.</p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;License</span></p>
<p>Unless otherwise stated, Origamers and/or its licensors own the intellectual property rights for all material on Origamers. All intellectual property rights are reserved. You may access this from Origamers for your own personal use subjected to restrictions set in these terms and conditions.</p>
<ul>
    <li>Republish material from OriGamers.</li>
    <li>Sell, rent or sub-license material from OriGamers.</li>
    <li>Reproduce, duplicate or copy material from OriGamers.</li>
    <li>Redistribute content from OriGamers.</li>
</ul>
<p>This Agreement shall begin on the date hereof. Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. OriGamers does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of OriGamers, its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, OriGamers shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OriGamers reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You warrant and represent that:</span></p>
<p>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</p>
<p>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</p>
<p>The Comments do not contain any defamatory, libellous, offensive, indecent or otherwise unlawful material which is an invasion of privacy.</p>
<p>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</p>
<p>You hereby grant OriGamers a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>
<p>Hyperlinking to our Content</p>
<p>The following organizations may link to our Website without prior written approval:</p>
<p dir="ltr" style="line-height:1.2;margin-top:14pt;margin-bottom:0pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Government agencies;</span></p>
<p>Search engines</p>
<p>News organizations</p>
<p>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses</p>
<p>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</p>
<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party&rsquo;s site.</p>
<p>We may consider and approve other link requests from the following types of organizations:</p>
<p>Commonly-known consumer and/or business information sources;</p>
<p>Dot.com community sites</p>
<p>Associations or other groups representing charities;</p>
<p>Online directory distributors;</p>
<p>Internet portals;</p>
<p>Accounting, law and consulting firms; and</p>
<p>Educational institutions and trade associations.</p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavourably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of OriGamers; and (d) the link is in the context of general resource information.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party&rsquo;s site.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to OriGamers. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Approved organizations may hyperlink to our Website as follows:</span></p>
<p>By use of our corporate name; </p>
<p>By use of the uniform resource locator being linked to; or</p>
<p>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party&rsquo;s site.</p>
<p>No use of OriGamers&apos;s logo or other artwork will be allowed for linking absent a trademark license agreement.</p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">I-Frames</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Content Liability</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libellous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third-party rights.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Your Privacy</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Please read Privacy Policy.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Reservation of Rights</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it&rsquo;s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:13.5pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Removal of links from our website</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:18pt; color: red !important; background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Disclaimer</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</span></p>
<p>Limit or exclude our or your liability for death or personal injury;</p>
 <p>Limit or exclude our or your liability for fraud or fraudulent misrepresentation;</p>
<p>Limit any of our or your liabilities in any way that is not permitted under applicable law; or</p>
<p>Exclude any of our or your liabilities that may not be excluded under applicable law.</p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:15pt;"><span style="font-size:12pt; color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</span></p>
<p><br></p>
<p><br></p>
        </div>
    </div>
    </div>
<style>
    *{
        list-style: none !important;
        white-space: inherit;
    }
    li p{margin: 0 !important;}
    .nav-pills .nav-link.active, .nav-pills .show>.nav-link{
        background-color: red;
    }
    *{color: white !important;}
</style>